# Tableau Météo

# bc4dc1     # Poupre
# cf80d3     # Poupre claire
# 00CEC8     # Bleu vert
# 90D5FF     # Bleu
# 52D6FC     # Bleu moyen
# 93E3FD     # Bleu claire
# 00ff13     # vert
# FFED52     # jaune 
# FDBA6F     # Orange
# FF5B61     # Rouge

views:
  - title: Home
    type: panel
    theme: LCARS Lower Decks I
    icon: mdi:home
    cards:
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
              - type: custom:layout-card
                layout_type: custom:horizontal-layout
                layout:
                  width: 300
                cards:
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: header-left
                    content: |
                      <h1>Intérieure (°C)</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: '{{ states(''sensor.maison_temperature'') }}'
                    tap_action:
                      action: none
                    card_mod:
                      style: |
                        ha-card {
                         --card-primary-font-size: 160px;
                          --card-primary-line-height: 161px !important;
                          text-align: center;
                          {% set teint = states('sensor.maison_temperature') | float(0) %}
                          {% if teint < 18 %} --card-primary-color:#bc4dc1;   # Poupre   
                          {% elif teint < 20 %} --card-primary-color:#90D5FF; # Bleu 
                          {% elif teint < 23 %} --card-primary-color:#00ff13; # vert  
                          {% elif teint < 25 %} --card-primary-color:#FFED52; # jaune 
                          {% else %} --card-primary-color:#FF5B61;            # Rouge
                          {% endif %} 
                        }
                      class: middle-left
                      
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: bar-left
                    content: |
                      <h1>Extérieure (°C)</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: >-
                      {{ states('sensor.tempest_st_00032986_temperature') |
                      round(1) }}
                    tap_action:
                      action: none
                    card_mod:
                      style: |
                        ha-card {
                          --card-primary-font-size: 160px;
                          --card-primary-line-height: 161px !important;
                          text-align: center;
                          {% set teext = states('sensor.tempest_st_00032986_temperature') | float(0) %}
                          {% if teext < -25 %} --card-primary-color:#bc4dc1;     # Poupre     
                          {% elif teext < -20 %} --card-primary-color:#cf80d3;   # Poupre claire 
                          {% elif teext < -15 %} --card-primary-color:#00CEC8;   # Bleu vert
                          {% elif teext < 0 %} --card-primary-color:#90D5FF;     # Bleu
                          {% elif teext < 15 %} --card-primary-color:#52D6FC;    # Bleu moyen
                          {% elif teext < 20 %} --card-primary-color:#93E3FD;    # Bleu claire
                          {% elif teext < 25 %} --card-primary-color:#00ff13;    # vert     
                          {% elif teext < 30 %} --card-primary-color:#FFED52;    # jaune 
                          {% elif teext < 35 %} --card-primary-color:#FDBA6F;    # Orange   
                          {% else %} --card-primary-color:#FF5B61;               # Rouge              
                          {% endif %} 
                        }
                      class: middle-left
                      
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: bar-left
                    content: |
                      <h1>Vistesse du vent (km/h)</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: >-
                      {{ states('sensor.tempest_st_00032986_wind_speed') |
                      round(1) }}
                    tap_action:
                      action: none
                    card_mod:
                      style: |
                        ha-card {
                          --card-primary-font-size: 160px;
                          --card-primary-line-height: 161px !important;
                          text-align: center;
                          {% set vent = states('sensor.tempest_st_00032986_wind_speed') | float(0) %}
                          {% if vent == 0 %} --card-primary-color:#FFFFFF;       # Blanc
                          {% elif vent < 10 %} --card-primary-color:#00ff13;     # vert     
                          {% elif vent < 15 %} --card-primary-color:#FFED52;     # jaune 
                          {% elif vent < 20 %} --card-primary-color:#FDBA6F;     # Orange   
                          {% else %} --card-primary-color:#FF5B61;               # Rouge              
                          {% endif %} 
                      class: middle-left
                      
                  - type: custom:html-card
                    title: ''
                    content: '&nbsp;'
                    card_mod:
                      class: footer-left
                      
          - type: vertical-stack
            cards:
              - type: custom:layout-card
                layout_type: custom:horizontal-layout
                layout:
                  width: 300
                cards:
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: header-left
                    content: |
                      <h1>[[sensor.date_du_jour]]</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: '{{ now().strftime(''%H:%M'') }}'
                    tap_action:
                      action: none
                    card_mod:
                      style: |
                        ha-card {
                          --card-primary-font-size: 160px;
                          --card-primary-line-height: 161px !important;
                          text-align: center;
                          --card-primary-color:#FFFFFF; # Blanc
                        }
                      class: middle-left
                      
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: bar-left
                    content: |
                      <h1>Index UV - Bruit(DB)</h1>

                  - type: custom:mushroom-template-card
                    primary: >-
                      {% set iuv = states('sensor.tempest_st_00032986_uv_index') | float(0)
                      %} {% if iuv > 0 %}
                         {{ states('sensor.tempest_st_00032986_uv_index') | round(2) }}
                      {% else %} 
                         {{ states('sensor.maison_bruit') | int(0) }}
                      {% endif %} 
                    tap_action:
                      action: none
                    card_mod:
                      style: |
                        ha-card {
                          --card-primary-font-size: 160px;
                          --card-primary-line-height: 161px !important;
                          text-align: center;
                          {% set iuv = states('sensor.tempest_st_00032986_uv_index') | float(0) %}
                          {% set bruit = states('sensor.maison_bruit') | int(0)  %}
                          {% if iuv > 0 %} 
                             {% if iuv < 3 %} --card-primary-color:#00ff13;       # Vert
                             {% elif iuv < 6 %} --card-primary-color:#FFED52;     # Jaune
                             {% elif iuv < 8 %} --card-primary-color:#FDBA6F;     # Orange
                             {% elif iuv < 11 %} --card-primary-color:#FF5B61;    # Rouge
                             {% else %} --card-primary-color:#bc4dc1;             # Poupre
                             {% endif %}
                          {% else %}
                             {% if bruit < 60 %} --card-primary-color:#00ff13;       # Vert
                             {% elif bruit < 90 %} --card-primary-color:#FFED52;     # Jaune
                             {% elif bruit < 110 %} --card-primary-color:#FDBA6F;    # Orange
                             {% elif bruit < 130 %} --card-primary-color:#FF5B61;    # Rouge
                             {% else %} --card-primary-color:#bc4dc1;                # Poupre
                             {% endif %}  
                          {% endif %} 
                          }      
                      class: middle-left
                      
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: bar-left
                    content: |
                      <h1>IQA</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: >-
                      {{
                      states('sensor.mauricie_quebec_canada_indice_de_qualite_de_l_air')
                      }} 
                    tap_action:
                      action: none
                    card_mod:
                      style: |
                        ha-card {
                          --card-primary-font-size: 160px;
                          --card-primary-line-height: 161px !important;
                          text-align: center;
                          {% set aqi = states('sensor.mauricie_quebec_canada_indice_de_qualite_de_l_air') | int(0) %}
                          {% if aqi < 50 %} --card-primary-color:#00ff13;        # Vert
                          {% elif aqi < 100 %} --card-primary-color:#FFED52;     # Jaune
                          {% elif aqi < 160 %} --card-primary-color:#FDBA6F;     # Orange
                          {% elif aqi < 200 %} --card-primary-color:#FF5B61;     # Rouge
                          {% else %} --card-primary-color:#bc4dc1;               # Poupre
                          {% endif %} 
                        }
                      class: middle-left
                      
                  - type: custom:html-card
                    title: ''
                    content: '&nbsp;'
                    card_mod:
                      class: footer-left
                      
          - type: vertical-stack
            cards:
              - type: custom:layout-card
                layout_type: custom:horizontal-layout
                layout:
                  width: 300
                cards:
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: header-left
                    content: |
                      <h1>Pluies (mm) - CO2</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: >-
                      {% set pluie = states('sensor.tempest_st_00032986_rain_today') | float(0) %}
                      {% if pluie < 1 %}
                         {{ states('sensor.maison_dioxyde_de_carbone') | int(0) }}
                      {% else %} 
                         {{ states('sensor.tempest_st_00032986_rain_today') | round(2) }}
                      {% endif %} 
                    tap_action:
                      action: none
                    card_mod:
                      style: |
                        ha-card {
                          --card-primary-font-size: 160px;
                          --card-primary-line-height: 161px !important;
                          text-align: center;
                          {% set pluie = states('sensor.tempest_st_00032986_rain_today') | float(0) %}
                          {% set co2 = states('sensor.maison_dioxyde_de_carbone') | int(0) %}
                          {% if pluie < 1 %}
                             {% if co2 < 800 %} --card-primary-color:#00ff13;     # Vert
                             {% elif co2 < 1200 %} --card-primary-color:#FFED52;  # Jaune
                             {% elif co2 < 1800 %} --card-primary-color:#FDBA6F;  # Orange
                             {% else %} --card-primary-color:#FF5B61;             # Rouge 
                             {% endif %}
                          {% else %}
                             {% if pluie < 10 %} --card-primary-color:#00ff13;       # Vert
                             {% elif pluie < 15 %} --card-primary-color:#FFED52;     # Jaune
                             {% elif pluie < 20 %} --card-primary-color:#FDBA6F;     # Orange
                             {% elif pluie < 25 %} --card-primary-color:#FF5B61;     # Rouge
                             {% else %} --card-primary-color:#bc4dc1;                # Poupre
                             {% endif %}  
                          {% endif %} 
                        }
                      class: middle-left
                      
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: bar-left
                    content: |
                      <h1>Humidité (%)-Taux (mm/h)</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: >-
                      {% set taux = states('sensor.tempest_st_00032986_rain_rate') | float(0)
                      %} {% if taux > 0 %}
                         {{ states('sensor.tempest_st_00032986_rain_rate') | round(2) }}
                      {% else %} 
                         {{ states('sensor.tempest_st_00032986_humidity') | round(1) }}
                      {% endif %} 
                    tap_action:
                      action: none
                    card_mod:
                      style: |
                        ha-card {
                          --card-primary-font-size: 160px;
                          --card-primary-line-height: 161px !important;
                          text-align: center;
                          {% set taux = states('sensor.tempest_st_00032986_rain_rate') | float(0) %}
                          {% if taux > 0 %}
                             {% if taux < 10 %} --card-primary-color:#00ff13;       # Vert
                             {% elif taux < 15 %} --card-primary-color:#FFED52;     # Jaune
                             {% elif taux < 20 %} --card-primary-color:#FDBA6F;     # Orange
                             {% else %} --card-primary-color:#FF5B61;               # Rouge
                             {% endif %} 
                          {% else %} 
                            --card-primary-color:#FFFFFF; # Blanc
                          {% endif %} 
                        }
                      class: middle-left
                  - type: custom:html-card
                    title: ''
                    card_mod:
                      class: bar-left
                    content: |
                      <h1>Pression (hPa)</h1>
                      
                  - type: custom:mushroom-template-card
                    primary: >-
                      {{ states('sensor.tempest_st_00032986_station_pressure') 
                      | round(1) }} 
                    tap_action:
                      action: none
                    card_mod:
                      style: |
                        ha-card {
                          --card-primary-font-size: 150px;
                          --card-primary-line-height: 161px !important;
                          text-align: center;
                          {% set niv = states('sensor.pression_determiner_etat') | int(0) %}
                          {% if niv == 1 %} --card-primary-color:#FFED52;   # Jaune
                          {% elif niv == 2 %} --card-primary-color:#00ff13; # Vert
                          {% else %} --card-primary-color:#FFFFFF;          # Blanc
                          {% endif %} 
                        }
                      class: middle-left
                  - type: custom:html-card
                    title: ''
                    content: '&nbsp;'
                    card_mod:
                      class: footer-left
  - type: panel
    path: parmetres
    title: Parmètres
    icon: mdi:tools
    theme: LCARS Lower Decks I
    cards:
      - type: vertical-stack
        cards:
          - type: custom:html-card
            title: ''
            content: '&nbsp;'
            card_mod:
              class: middle-blank
              
          - type: custom:html-card
            title: ''
            content: |
              <h1>Paramètres</h1>
            card_mod:
              class: header-contained
              
          - type: entities
            entities:
              - entity: input_boolean.lcars_sound
                icon: mdi:speaker
              - entity: input_boolean.lcars_texture
                icon: mdi:texture
              - entity: input_number.lcars_horizontal
              - entity: input_number.lcars_vertical
            state_color: true
            card_mod:
              class: middle-contained
          - type: custom:html-card
            title: ''
            content: |
              <h1>&nbsp;</h1>
            card_mod:
              class: footer-contained
